#ifndef BASALOPERAIREMOTEUI_GLOBAL_H
#define BASALOPERAIREMOTEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASALOPERAIREMOTEUI_LIBRARY)
#  define BASALOPERAIREMOTEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASALOPERAIREMOTEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASALOPERAIREMOTEUI_GLOBAL_H
