#ifndef BRIDGEICLIENT_GLOBAL_H
#define BRIDGEICLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BRIDGEICLIENT_LIBRARY)
#  define BRIDGEICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BRIDGEICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BRIDGEICLIENT_GLOBAL_H
