#ifndef UNSTRUCTOPERAIREMOTEUI_GLOBAL_H
#define UNSTRUCTOPERAIREMOTEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNSTRUCTOPERAIREMOTEUI_LIBRARY)
#  define UNSTRUCTOPERAIREMOTEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNSTRUCTOPERAIREMOTEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNSTRUCTOPERAIREMOTEUI_GLOBAL_H
