#ifndef STRUCTICLIENT_GLOBAL_H
#define STRUCTICLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRUCTICLIENT_LIBRARY)
#  define STRUCTICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRUCTICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STRUCTICLIENT_GLOBAL_H
