#ifndef UNSTRUCTOPERAISERVER_GLOBAL_H
#define UNSTRUCTOPERAISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNSTRUCTOPERAISERVER_LIBRARY)
#  define UNSTRUCTOPERAISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNSTRUCTOPERAISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNSTRUCTOPERAISERVER_GLOBAL_H
