#ifndef SCHEDULEOPERAIREMOTEUI_GLOBAL_H
#define SCHEDULEOPERAIREMOTEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCHEDULEOPERAIREMOTEUI_LIBRARY)
#  define SCHEDULEOPERAIREMOTEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCHEDULEOPERAIREMOTEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCHEDULEOPERAIREMOTEUI_GLOBAL_H
