#ifndef STRUCTOPERAIREMOTEUI_GLOBAL_H
#define STRUCTOPERAIREMOTEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRUCTOPERAIREMOTEUI_LIBRARY)
#  define STRUCTOPERAIREMOTEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRUCTOPERAIREMOTEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STRUCTOPERAIREMOTEUI_GLOBAL_H
