#ifndef NETICLIENTLIB_GLOBAL_H
#define NETICLIENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETICLIENTLIB_LIBRARY)
#  define NETICLIENTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETICLIENTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETICLIENTLIB_GLOBAL_H
