#ifndef BASALOPERAISERVER_GLOBAL_H
#define BASALOPERAISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASALOPERAISERVER_LIBRARY)
#  define BASALOPERAISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASALOPERAISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASALOPERAISERVER_GLOBAL_H
