#ifndef BASEISERVERLIB_GLOBAL_H
#define BASEISERVERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEISERVERLIB_LIBRARY)
#  define BASEISERVERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASEISERVERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEISERVERLIB_GLOBAL_H
