#ifndef BASEIREMOTELIB_GLOBAL_H
#define BASEIREMOTELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEIREMOTELIB_LIBRARY)
#  define BASEIREMOTELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASEIREMOTELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEIREMOTELIB_GLOBAL_H
