#ifndef MONITORISERVER_GLOBAL_H
#define MONITORISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MONITORISERVER_LIBRARY)
#  define MONITORISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MONITORISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MONITORISERVER_GLOBAL_H
