#ifndef DATABASELIB_GLOBAL_H
#define DATABASELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASELIB_LIBRARY)
#  define DATABASELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASELIB_GLOBAL_H
