/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "upcloudddmilib_global.h"
/* Header for class com_upcloud_ddmi_core_DDMIService */

#ifndef _Included_com_upcloud_ddmi_core_DDMIService
#define _Included_com_upcloud_ddmi_core_DDMIService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_upcloud_ddmi_core_DDMIService
 * Method:    startup
 * Signature: ()V
 */
UPCLOUDDDMILIBSHARED_EXPORT JNIEXPORT void JNICALL Java_com_upcloud_ddmi_core_DDMIService_startup
  (JNIEnv *env, jobject obj,jstring ddmiPath);

/*
 * Class:     com_upcloud_ddmi_core_DDMIService
 * Method:    destory
 * Signature: ()V
 */
UPCLOUDDDMILIBSHARED_EXPORT JNIEXPORT void JNICALL Java_com_upcloud_ddmi_core_DDMIService_destory
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
