#ifndef BASEICLIENTLIB_GLOBAL_H
#define BASEICLIENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEICLIENTLIB_LIBRARY)
#  define BASEICLIENTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASEICLIENTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEICLIENTLIB_GLOBAL_H
