#ifndef UNSTRUCTICLIENT_GLOBAL_H
#define UNSTRUCTICLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNSTRUCTICLIENT_LIBRARY)
#  define UNSTRUCTICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNSTRUCTICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNSTRUCTICLIENT_GLOBAL_H
