#ifndef OPERAICLIENT_GLOBAL_H
#define OPERAICLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPERAICLIENT_LIBRARY)
#  define OPERAICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPERAICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERAICLIENT_GLOBAL_H
