#ifndef TRANSMSGLIB_GLOBAL_H
#define TRANSMSGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSMSGLIB_LIBRARY)
#  define TRANSMSGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRANSMSGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSMSGLIB_GLOBAL_H
