#ifndef HTHROBSISERVER_GLOBAL_H
#define HTHROBSISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTHROBSISERVER_LIBRARY)
#  define HTHROBSISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HTHROBSISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTHROBSISERVER_GLOBAL_H
