#ifndef UNSTRUCTISERVER_GLOBAL_H
#define UNSTRUCTISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNSTRUCTISERVER_LIBRARY)
#  define UNSTRUCTISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNSTRUCTISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNSTRUCTISERVER_GLOBAL_H
