#ifndef HTHROBSIREMOTE_GLOBAL_H
#define HTHROBSIREMOTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTHROBSIREMOTE_LIBRARY)
#  define HTHROBSIREMOTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define HTHROBSIREMOTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTHROBSIREMOTE_GLOBAL_H
