#ifndef HTHROBSICLIENT_GLOBAL_H
#define HTHROBSICLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTHROBSICLIENT_LIBRARY)
#  define HTHROBSICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HTHROBSICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTHROBSICLIENT_GLOBAL_H
