#ifndef TIMERICLIENTLIB_GLOBAL_H
#define TIMERICLIENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIMERICLIENTLIB_LIBRARY)
#  define TIMERICLIENTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIMERICLIENTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIMERICLIENTLIB_GLOBAL_H
