#ifndef NETIREMOTEUILIB_GLOBAL_H
#define NETIREMOTEUILIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETIREMOTEUILIB_LIBRARY)
#  define NETIREMOTEUILIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETIREMOTEUILIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETIREMOTEUILIB_GLOBAL_H
