#ifndef STRUCTOPERAISERVER_GLOBAL_H
#define STRUCTOPERAISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRUCTOPERAISERVER_LIBRARY)
#  define STRUCTOPERAISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRUCTOPERAISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STRUCTOPERAISERVER_GLOBAL_H
