#ifndef TIMERIREMOTEUILIB_GLOBAL_H
#define TIMERIREMOTEUILIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIMERIREMOTEUILIB_LIBRARY)
#  define TIMERIREMOTEUILIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIMERIREMOTEUILIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIMERIREMOTEUILIB_GLOBAL_H
