#ifndef WORKTHREADPOOL_GLOBAL_H
#define WORKTHREADPOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORKTHREADPOOL_LIBRARY)
#  define WORKTHREADPOOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WORKTHREADPOOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WORKTHREADPOOL_GLOBAL_H
