#ifndef SCHEDULEOPERAISERVER_GLOBAL_H
#define SCHEDULEOPERAISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCHEDULEOPERAISERVER_LIBRARY)
#  define SCHEDULEOPERAISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCHEDULEOPERAISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCHEDULEOPERAISERVER_GLOBAL_H
