#ifndef BASALISERVER_GLOBAL_H
#define BASALISERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASALISERVER_LIBRARY)
#  define BASALISERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASALISERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASALISERVER_GLOBAL_H
