#ifndef OPERAIREMOTE_GLOBAL_H
#define OPERAIREMOTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPERAIREMOTE_LIBRARY)
#  define OPERAIREMOTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPERAIREMOTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERAIREMOTE_GLOBAL_H
