#ifndef MONITORICLIENT_GLOBAL_H
#define MONITORICLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MONITORICLIENT_LIBRARY)
#  define MONITORICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MONITORICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MONITORICLIENT_GLOBAL_H
